---
# docker_edition: "ce"
# docker_channel: "edge"

docker_version: "18.05.0"

docker_users: []

docker_cron_tasks:
  - job: docker system prune -f
    name: "Docker clean up"
    schedule: ["0", "0", "*", "*", "0"]

docker_daemon_options: []
docker_daemon_environment: []

docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_repository: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} edge"
# docker_apt_package_name: "{{ docker_version }}~{{ docker_edition }}~3-0~{{ ansible_distribution | lower }}"
docker_apt_package_name: "18.05.0~ce~3-0~raspbian"
docker_apt_cache_time: 86400
