---
- hosts: all
  roles:
    - k8s-pi
- hosts: master
  tasks:
    - name: kubeadm resest just in case
      shell: kubeadm reset -f
      become: True
      tags:
        - clean
        - init_cluster

   #  - shell: kubeadm token create --print-join-command
   #    register: results
   #  - debug:
   #      var: results.stdout
   #  - set_fact:
   #      token: "{{ results.stdout | regex_search(regexp, '\\2') | first }}"
   #    vars:
   #      regexp: '([^\s]+\s){4}([^\s]+)'
   #  - debug:
   #      var: token
   #  - set_fact:
   #      hash: "{{ results.stdout | regex_search(regexp, '\\2') | first }}"
   #    vars:
   #      regexp: '([^\s]+\s){6}([^\s]+)'
   #  - debug:
   #      var: hash

    - name: generate a token 
      shell: kubeadm token generate
      become: True
      register: token
      tags:
        - init_cluster

    - name: initialize kube cluster
      shell: kubeadm init --token "{{token.stdout}}"
      become: True
      tags:
        - init_cluster

    # CONFIGURE Kubectl:
    # > mkdir -p $HOME/.kube           
    # > sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
    # > sudo chown $(id -u):$(id -g) $HOME/.kube/config

    # Due to problem getting home path of the right user 
    # register the path in a var
    - name: get HOME path of user pi
      shell: echo $HOME
      register: pi_home
      tags:
        - init_cluster
        - init_kubectl

    - name: Remove .kube directory 
      file:
        path: "{{pi_home.stdout}}/.kube/"
        state: absent
      tags:
        - init_kubectl
        - clean_up

    - name: Create a directory for kube conf
      file:
        path: "{{pi_home.stdout}}/.kube"
        state: directory
        mode:  0755
      tags:
        - init_kubectl
        - init_cluster

    - name: copy admin.conf using shell
      shell: cp -i /etc/kubernetes/admin.conf  "{{pi_home.stdout}}/.kube/config"
      become: True
      tags:
        - init_cluster
        - init_kubectl

    - name: get user id
      shell: id -u
      register: user_id
      tags: 
        - init_cluster
        - init_kubectl

    - name: get user group
      shell: id -g
      register: user_group_id
      tags:
        - init_cluster
        - init_kubectl

    - name: change rights of config file
      file:
        path:  "{{pi_home.stdout}}/.kube/config"
        owner: "{{user_id.stdout}}"
        group: "{{user_group_id.stdout}}"
        mode: 0600
      become: yes
      tags:
        - init_cluster
        - init_kubectl   

- hosts: nodes 
  tasks:
    - name: Join cluster 
      shell: kubeadm join   
